oclif/oclif

README.md

Since emoji headings were introduced in https://github.com/oclif/oclif/commit/fb7765cf6e6aee9be110eab94e596cdc85c323dc, the links to headings were broken at a few points.
I took the chance to validate all the links in the readme (via [remark](https://remark.js.org/)) and fix them.
The only outlier is "Other Command Options", as the cog seems to have a variation selector in front, which makes GitHub treat the anchor as `#%EF%B8%8F-other-command-options`. We could potentially hardcore the link to this, but maybe we can find a different solution to this.

Fix anchor links to headings

---

src/command_base.ts

Yeomans env.run doesn't seem to return a promise, but takes a callback.

fix: return a promise from yeoman callback style so it actually awaits

---

templates/README.md.ejs

As mentioned in #70, this commit removes the Greenkeeper badge from the readme template.  If you feel I've missed something or need to make other changes, please let me know, and I'd be happy to take care of it.

Remove Greenkeeper readme template badge

---

src/generators/command.ts

I think we could have an even nicer error message here, but this is the obvious quick fix.
Fixes #91

fix(generators/command): assert cwd is a project

---

README.md

Let's add the `oclif` image to the README, similar to how it's done on https://github.com/atom/atom/blob/master/README.md.
I don't have access to the image, but put a placeholder where it should likely go. 👍

Adding oclif logo to README

---

README.md

This will fix the typo in the link to typescript plugin example repo. in the readme file.

Update README.md: Fixed example links

---

templates/src/command.js.ejs

This is for JavaScript-based commands. See discussion in https://github.com/oclif/oclif/issues/120

Fix command descriptions not showing up in the help

---

src/generators/app.ts
templates/README.md.ejs
templates/appveyor.yml.ejs
templates/circle.yml.ejs

Decided to just finish of all the optional add-on issues, as with the other two I've made it active by default, I also added a check in appveyor.yml to ensure mocha is there too, mirroring the circle.yml
Fixes #71

feat: make codecov optional

---

src/generators/app.ts

Debating whether this should be set to `latest` or just have to manually update. Eslint is now on major version 5, so this should reflect that...

fix: update eslint to latest major in generator

---

templates/LICENSE.mit

There might be a better fix for #240 that makes the year dynamic, but this may work for a quick and temporary solution.

Update license template copyright year

---

templates/tsconfig.json

See https://spectrum.chat/oclif/general/lib-folder-is-not-found-in-npm-publish-component~b74ef8d9-96c4-46bd-9893-7cdcca8542fb
Fixes https://github.com/oclif/oclif/issues/246

set "composite": false

---

templates/travis.yml.ejs

fix: use correct path separators in travis.yml template

---

README.md

Closes #311 
As discussed in the issue, this PR attempts to remove or replace as many instances of condescending or isolating language (ie. simple, easy, just, etc) as possible in the documentation.
There are some instances where a change wasn't _necessary_ but I still felt like it would be beneficial, but of course, feel free to revert. If even a fraction of these changes can be merged then it will be a huge step towards making this repo more inclusive!
Next step (if it's alright): Tackling https://github.com/oclif/oclif.github.io

Add more inclusive language to README

---

.circleci/release

Currently the release job is failing on CircleCI due to the following error:
```
+ semantic-release -e @oclif/semantic-release
[10:22:26 AM] [semantic-release] › ℹ  Running semantic-release version 15.14.0
[10:22:26 AM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Cannot find module '@semantic-release/exec'
```
[Check out an example failed job](https://app.circleci.com/pipelines/github/oclif/oclif/240/workflows/e567f2b1-35a1-4cd2-b335-e5a743328b42/jobs/19634)
I couldn’t pin down exactly why `@semantic-release/exec` was unavailable, but @RasPhilCo suggested bumping to semantic-release v17.
In my testing in a docker environment similar to circle (using `node:latest`) the results seem encouraging:
```
[11:28:01 AM] [semantic-release] › ℹ  Running …
```

chore(deps-dev): bump semantic-release from 15 to 17

---

src/commands/promote.ts

explanation:
oclif upload tarballs with a 604800 max-age.  https://github.com/oclif/oclif/blob/711132e6a29ba82e370a5c90cc5059682c389a0f/src/commands/upload/tarballs.ts#L50
when we promote them, oclif uses copyobject which maintains those metadata/headers
```
$ aws s3api head-object --bucket dfc-data-production --key media/salesforce-cli/sfdx/channels/stable-rc/sfdx-win32-x86.tar.gz 
bytes   max-age=604800  40467686        application/gzip        "08bb2db16b33c5f0ba78e8b1232762ee"      2021-05-06T17:39:20+00:00       H924njmMRBpURBYiOh1DaQYS7OJcbVI8
$ aws s3api head-object --bucket dfc-data-production --key media/salesforce-cli/sfdx/channels/stable/sfdx-win32-x86.tar.gz 
bytes   max-age=604800  40466572        application/gzip        "c03e7193914a3883f0ebc8c15cdbb16a" …
```

fix: respect cache on promote

---

package.json

Take a look at the release job, it is failing by trying to use `bin/dev` which only works if the lib is build. This uses bin/dev to create the manifest and readme for releasing.

build: use bin/dev to create manifest & readme

---

README.md
bin/dev
package.json
src/commands/generate/command.ts
src/commands/generate/hook.ts
src/generators/cli.ts
src/generators/command.ts
src/generators/hook.ts
src/types/index.ts
templates/src/command.ts.ejs
templates/src/hook.ts.ejs
templates/test/command.test.ts.ejs
templates/test/hook.test.ts.ejs

- Restores the `hook` and `command` commands from v1 as `generate:hook` and `generate:command`, respectively. 
- Updates REAMDE with notes about migrating from v1 to v2
Fixes #767 
@W-10386078@

Restore hook and command generators

---

src/tarballs/build.ts
src/tarballs/node.ts

This replaces https://github.com/oclif/dev-cli/pull/416.
This PR just adds quotes around a few raw paths used during tarball packing, ensuring that these steps work when run in a path containing spaces.
I've tested this in my project, and everything now seems to build correctly when running `oclif pack tarballs`.

Fix tarball packing in paths with spaces

---

src/commands/pack/macos.ts

Reverts the functionality for building M1 `.pkg` files.
This will be re-added correctly with https://github.com/oclif/oclif/pull/849.
Closes #854

fix: revert building mac m1 packages, wait for PR #849

---

src/commands/pack/macos.ts

This removes outdated code that was accidentally re-introduced by bad conflict resolution on a merge.
The code was re-added to main when this commit, https://github.com/oclif/oclif/commit/e5b68af8510b0419ec48d76087ed0bec61fc81ad, to revert some changes was added. This caused merge conflicts with the PR that added the M1 functionality, https://github.com/oclif/oclif/pull/849, and those were incorrectly resolved when it was merged.
Fixes #865

Fix `oclif pack macos`

---

src/command-base.ts
src/commands/generate.ts
src/commands/generate/command.ts
src/commands/generate/hook.ts

Properly await yeoman generators so that the flush timeout doesn't trigger before the user can complete the prompts
Fixes #922

fix: await yeoman generators

---

src/commands/readme.ts
test/fixtures/cli-command-with-alias/README.md
test/fixtures/cli-command-with-alias/package.json
test/fixtures/cli-command-with-alias/src/commands/hello.ts
test/fixtures/cli-command-with-alias/src/help.ts
test/fixtures/cli-command-with-alias/src/index.ts
test/fixtures/cli-command-with-alias/tsconfig.json
test/unit/readme.test.ts

This is to allow for `--no-aliases` so the README being generated for a plugin does not include aliases, which may clutter the documentation.
Example usage in `package.json`:
```json
{
"scripts": {
"prepack": "oclif manifest && oclif readme --no-aliases"
}
}
```

feat: add `--aliases` flag for readme command

---

src/commands/readme.ts
test/fixtures/cli-command-with-alias/README.md
test/fixtures/cli-command-with-alias/package.json
test/fixtures/cli-command-with-alias/src/commands/hello.ts
test/fixtures/cli-command-with-alias/src/help.ts
test/fixtures/cli-command-with-alias/src/index.ts
test/fixtures/cli-command-with-alias/tsconfig.json
test/unit/readme.test.ts

* feat: add `--aliases` flag for readme command
* fix: create test fixture to test --no-aliases flag
* fix: eslint issues

feat: add `--aliases` flag for readme command (#925)

---

src/commands/readme.ts

This PR adds the missing `toc` tag to the description for the `readme` command.

fix: add toc tag to readme command description

---

src/commands/pack/win.ts

fixes an error previously tested on the `beta` prerelease tag that didn't make it into the main PR

fix: win pack error

---

src/version-indexes.ts

`folder` property on `pjson.oclif.s3` was being used by the `--indexes` but wasn't being checked for.
fix #1062
Now, it's optional

fix: make oclif.s3.folder optional for --indexes

---

src/commands/manifest.ts

wireit does not play nicely with child_process and shelljs. We can work around this by using `yarn tsc` instead of `yarn build` for compiling the JIT plugins during manifest generation.

fix: workaround wireit

---

src/commands/manifest.ts

Fixes issue with running `oclif manifest` on plugins that still use deprecated `cli-engine`

fix: check if oclif section exists

---

src/commands/manifest.ts

Prevents `npm` command executions from inheriting the process' `npm_config_tag` during publish

fix: explicitly ask for latest from npm

---

.gitignore
package.json
src/commands/pack/macos.ts
yarn.lock

@W-12545440@
adds symlinks from the `binAliases` section in pjson
requires: https://github.com/oclif/core/pull/632

feat: create symlinks from binAliases to bin for pack:macos

---

package.json
src/generators/cli.ts
src/generators/command.ts
src/generators/hook.ts
src/types/index.ts
test/integration/deb.test.ts
test/integration/macos.test.ts
test/integration/publish.test.ts
yarn.lock

- Removes `PackageJson` type in favor of @oclif/core's `Interfaces.PJSON`
- Removes `yosay` dependency
- Removes `oclif2` bin alias used for testing
@W-12153783@
@W-13825265@

fix: remove yosay dependency

---

src/commands/readme.ts
yarn.lock

Closes https://github.com/oclif/oclif/issues/1128
`oclif readme` would miss the `See code` block in CLIs using spaces as a topic separator.
Test:
1) clone https://github.com/cristiand391/sf-plugin-api
2) run `yarn oclif readme`, no `See code` in readme
3) yarn link this PR into the plugin, repeat step 2.
@W-13872809@

fix: respect topic sep when generating readme

---

src/commands/pack/win.ts

When a windows signing cert expires, all past `exe` files signed with that certificate also show as expired. Even if they were signed during a time that the cert was still valid. It looks like we can pass a timestamp (from a timestamp authority) that will allow old files signed before expiration to still show as valid. 
This can useful when an windows cert expires, users could be instructed to install an old `exe` and then run `<bin> update` to get the latest version. 
[@W-13992209@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-13992209)
[Information on timestamp validation](https://codesigningstore.com/code-signing-architecture-how-it-works#:~:text=Time%20Stamp%20Authority%20(TSA),-Code%20Signing%20process&text=Although%20this%20part%20is%20optional,signature%20is% …

Add a timestamp authority to win:pack

---

src/commands/lock.ts

Adds `lock` command for copying `yarn.lock` to `oclif.lock`. See https://github.com/oclif/plugin-plugins/pull/648 for more context
@W-14010705@

feat: add lock command

---

package.json
src/commands/manifest.ts
src/tarballs/node.ts
src/util.ts
test/integration/sf.test.ts

For jit plugins `manifest` now downloads and extracts the npm package to get the `oclif.manifest.json` for the specified version. This is significantly faster than cloning and building each JIT plugin's repository
@W-14122700@

feat: improve perf of manifest command

---

src/commands/manifest.ts

I _think_ this will fix this error:
`xz: (stdin): File format not recognized` ([action run](https://github.com/salesforcecli/cli/actions/runs/6263970294/job/17009588881?pr=1162#step:6:11))
The tarball we are downloading from `npm` uses `gz` compression, not `xz`. This PR switches from using the `-J` flag to `-z`. This still works locally on a Mac (I added a temp log to confirm it was linked correctly):
I also did a diff on manifests generated before and after this change and they were the same.
[@W-14122700@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-14122700)

fix: extract gz not xz

---

src/commands/pack/win.ts

WINDOWS_SIGNING_PASS isn't required unless you want to sign the installer

docs: windows env/config explanation

---

src/tarballs/build.ts

Newer versions of yarn depend on more files than "yarn.lock". As a result, the tarballs need to include these core files to ensure that any future commands against the tarball contents utilize the right version of `yarn`.
Configuring yarn v4 with a "pinned version" requires the ".yarnrc.yml" file along with the `yarnPath` configuration value. If configured to use a specific version of yarn, Yarn will download required files into a "./.yarn/releases/" directory. In the future, any execution of `yarn` will pick up the `yarnPath` configuration and use the "./.yarn/releases/" directory contents to download and use the specific version of yarn.
Without these changes, modern versions of `yarn`, like Yarn v4, do not properly install their dependencies when packaging for release. For example, if …

fix: missing core yarn files

---

src/tarballs/build.ts

Merges #1229 
* fix: missing core yarn files
Newer versions of yarn depend on more files than "yarn.lock". As a result, the tarballs need to include these core files to ensure that any future commands against the tarball contents utilize the right version of `yarn`. Example: configuring yarn v4 with a "pinned version" requires the ".yarnrc.yml" file along with the `yarnPath` configuration value. If configured to use a specific version of yarn, Yarn will download required files into a "./.yarn/releases/" directory. In the future, any execution of `yarn` will pick up the `yarnPath` configuration and use the "./.yarn/releases/" directory contents to download and use the specific version of yarn.
* fix: yarn root path

fix: missing core yarn files (#1229)

---

package.json
src/commands/manifest.ts
src/commands/readme.ts
tsconfig.json
yarn.lock

Bump all `@oclif` deps to latest major versions
might fix #1227

fix: bump oclif deps

---

src/commands/readme.ts

This fixes issue #1232. I replaced the string pattern in the call to `commandDir.replace` with a RegEx that will accept either `./` or `.\`. As per the [node docs](https://nodejs.org/api/path.html#pathsep), the only two possible values for `path.sep` are / for POSIX and \ for Windows. Thus, I don't see any issue replacing the path.sep with the RegEx to check for the / or \ characters.

fix: readme command does not parse path correctly on windows

---

src/commands/readme.ts
test/integration/cli.test.ts

Fixes the regex used for finding the `outDir` during readme generation

fix: outdir regex in readme

---

src/tarballs/bin.ts
src/tarballs/build.ts
src/tarballs/config.ts

Allow specifying [options to the Node process](https://nodejs.org/api/cli.html#options) when creating the CLI binary in the `pack:tarballs` command.
Example of useful options include:
- [`--max-old-space-size=...`](https://nodejs.org/api/cli.html#--max-old-space-sizesize-in-megabytes) to increase memory size
- [`--disable-warning=...`](https://nodejs.org/api/cli.html#--disable-warningcode-or-type) to disable warnings, e.g, `ExperimentalWarning`
The list of options can be specified as a string array or space-separated string in the `oclif.update.node.options` section of the `package.json`:
example:
```json
{
"oclif": {
"update": {
"node": {
"options": ["--max-old-space-size=4096", "--no-warnings"]
}
}
}
}
```
or:
```json
{
"oclif": {
"update": {
"node": {
"options": …
```

feat: add node.options

---

package.json
src/tarballs/build.ts

Copy the `.yarn/plugins` directory (if it exists) when packing tarballs

fix: copy .yarn/plugins directory

---

src/commands/promote.ts

Merges #1266 
Fixes #1265
* fix: correct S3 key generation for /apt/./ During deb artifacts promotion (#1265)
* fix: typo

fix: correct S3 key generation for /apt/./ During deb artifacts promotion (#1265) (#1266)

---

src/commands/lock.ts

Deprecate and hide the `lock` command since the `oclif.lock` feature will not be supported in the next major version of `@oclif/plugin-plugins` (see https://github.com/oclif/plugin-plugins/pull/776)

feat: deprecate and hide lock command

---

src/commands/pack/win.ts

If the path to the project contains a whitespace, makensis fails without any info. Adding quotation marks will fix the failing part.

Update win.ts and fix error by adding quotation marks

---

src/commands/pack/win.ts

Unfortunately after the changes in #1210 we are still seeing the option to exclude the LOCALAPPDATA directory from Windows Defender scans when installing the Heroku CLI on Windows when the installer has been built with the `--defender-exclusion hidden` option (though it is no longer selected by default).
The fix in this PR should completely remove the section that sets the Windows Defender exclusion options from the template string built by the `pack win` command for use with NSIS.

fix: update logic for exclusion from Windows Defender scans

---

src/commands/generate/hook.ts
src/generators/hook.ts

Respect tsconfig.json's `outDir` when composing path for generated hook
Fixes #1196
@W-14251792@

fix: respect tsconfig outDir when generating hook

---

package.json
src/generators/cli.ts
src/util.ts
test/unit/util.test.ts
yarn.lock

- validate that provided package name is valid (using `validate-pkg-name` library)
- validate that provided `bin` is valid
Fixes #1310 
@W-15161093@

fix: validate package name and bin

---

src/tarballs/build.ts

Currently oclif/oclif uses a lot of bash in order to build applications and natively does not support windows runners such as cmd and pwsh. However, this can be worked around using wsl or github actions `bash` runner (even on windows machines).
Almost everything works and allows us to build with it in these bash environments, however, the only step that fails is this extract step because a Windows path will look like `C:\some\path` and tar will natevely interpret anything with a `:` as an IP: https://superuser.com/questions/1720172/what-does-tar-cannot-connect-to-resolve-failed-mean
We can't use this for win/macOS runners however as the `tar` cli in there does not support it: https://github.com/r-lib/remotes/issues/171
This just adds the --force-local flag to windows builds making much …

fix: force local paths when extracting on win32

---

docs/generate.md
src/commands/generate.ts

When generating a new CLI, there's now only yarn and npm in the list. `pnpm` is quite popular and widely used, so It would be great to have `pnpm` option available in the list too.

feat: add `pnpm` to the list of supported package managers

---

src/commands/pack/deb.ts
src/commands/pack/macos.ts
src/commands/pack/tarballs.ts
src/commands/pack/win.ts

- Document `pretarball` script in the help for the `pack` commands
- Add note about prereqs for `oclif pack win`
Fixes https://github.com/oclif/oclif.github.io/issues/224
@W-15285420@

fix: doc pretarball in help

---

templates/src/command.ts.ejs

Allows the file generated by `oclif generate command NAME` to compile when `noImplicitOverride` is turned on in `tsconfig.json`.
Addresses #1354.

Add `override` modifier to static properties in generated commands

---

templates/src/command.ts.ejs

Allows the file generated by `oclif generate command NAME` to compile when `noImplicitOverride` is turned on in `tsconfig.json`.
Fixes #1354.

Add `override` modifier to generated commands (#1356)

---

src/commands/generate.ts
test/integration/cli.test.ts

Remove `yarn.lock` if the selected package manager is npm or pnpm

fix: remove yarn.lock if yarn wasnt selected

---

src/commands/init.ts
templates/src/init/dev.cmd.ejs
templates/src/init/dev.js.ejs
templates/src/init/run.cmd.ejs
templates/src/init/run.js.ejs

This adds a new command, `init`, that adds the necessary files and configuration to an existing npm project. It attempts to auto-detect the module type and package manager being used, falling back to a prompt if necessary. Usage is covered in the examples. 
Addresses #999

feat: Add init command

---

src/commands/generate.ts

- reset version to `0.0.0` in package.json of generated cli
- remove `.github/workflows/automerge.yml` in generated cli

fix: reset version on generated cli

---

package.json
src/commands/readme.ts
yarn.lock

When a plugin's tsconfig file contains comments or trailing commas, `oclif readme` fails to read the tsconfig file because it's expecting well-formed JSON, not JSONC. As far as I can tell, it's trying to read the compilerOptions.outDir value from the tsconfig, but only to check if the output folder exists. It logs a warning, but the command seems to find everything it's supposed to despite the warning.
In this PR, I use [tiny-jsonc](https://www.npmjs.com/package/tiny-jsonc) to parse the tsconfig instead of JSON.parse. The code is more verbose, and I'm not sure introducing a new dependency just for a clearer warning message is worth it.
An alternative might me to load the oclif.commands value from package.json and check that instead. I don't know if that's similar enough to the existing …

fix(readme): read tsconfigs as JSONC instead of JSON

---

package.json

Probably the last one of this series. 
[plugin-not-found](https://github.com/oclif/plugin-not-found/releases/tag/3.1.9) has updated its dependencies with fixed versions of lodash vulnerability.
Just bumping this version to include the new updates

chore: bump plugin-not-found version

---

templates/cli/commonjs/.vscode/launch.json.ejs
templates/cli/esm/.vscode/launch.json.ejs

Generate separate `.vscode/launch.json` for ESM and CommonJS
**Testing**
- `bin/dev.js generate launch-test-cjs --output-dir ~/code --yes --module-type CommonJS`
- `bin/dev.js generate launch-test-esm --output-dir ~/code --yes --module-type ESM`
- open `launch-test-cjs` in vscode, put breakpoint in `src/commands/hello/world.ts`, launch `Execute Command` from debugger panel. Debugger should pause on breakpoint
- open `launch-test-esm` in vscode, put breakpoint in `src/commands/hello/world.ts`, launch `Execute Command` from debugger panel. Debugger should pause on breakpoint
Fixes #1438 
@W-15959529@

fix: launch config for ESM

---

src/commands/upload/tarballs.ts
src/tarballs/build.ts

- Warn about missing `buildmanifest` during `pack` if s3 bucket or host are not set
- Allow `upload` to succeed when `buildmanifest` doesn't exist and print warning
Fixes #1447 
@W-15993332@

fix: allow upload to succeed without buildmanifest

---

src/tarballs/build.ts

Fixes the issue here https://github.com/oclif/oclif/issues/1526
I have tested the fix for building and packing the tarball in my local environment.
We do not use a `pretarball` script, but hopefully that helps someone in the future. Tested it with a simple script and got no errors.

fix: add pnpm lock option

---

src/aws.ts
src/commands/promote.ts
src/commands/upload/deb.ts
src/commands/upload/macos.ts
src/commands/upload/tarballs.ts
src/commands/upload/win.ts
src/version-indexes.ts

- Improve logging in `oclif promote`
- Add `--dry-run` flag to following commands:
- `oclif promote`
- `oclif upload deb`
- `oclif upload macos`
- `oclif upload tarballs`
- `oclif upload win`
```
❯ ~/repos/oclif/oclif/bin/run.js promote --macos --sha 0cbb3a0 --channel stable --version 2.60.13 --dry-run --win --xz --deb --indexes
Promoting v2.60.13 (0cbb3a0) to stable channel
> sf-linux-x64-buildmanifest
action: copy
source: s3://dfc-data-production/media/salesforce-cli/sf/versions/2.60.13/0cbb3a0/sf-v2.60.13-0cbb3a0-linux-x64-buildmanifest
target: s3://dfc-data-production/media/salesforce-cli/sf/channels/stable/sf-linux-x64-buildmanifest
> sf-linux-x64.tar.gz
action: copy
source: s3://dfc-data-production/media/salesforce-cli/sf/versions/2.60.13/0cbb3a0/sf-v2.60.13-0cbb3a0-linux-x64.tar.gz …
```

fix: improve logging in promote

---

src/commands/manifest.ts

If `files` is missing from the package.json, `oclif manifest` would throw an unhelpful error
```
TypeError: Cannot read properties of undefined (reading 'find')
```
This makes sure that the user knows how to fix the issue

Add explicit error when `files` is missing from package.json

---

src/commands/manifest.ts

If `files` is missing from the package.json, `oclif manifest` would throw an unhelpful error
```
TypeError: Cannot read properties of undefined (reading 'find')
```
This makes sure that the user knows how to fix the issue

fix: add explicit error when `files` is missing from package.json (#1577)

---

src/commands/readme.ts

👋  I'd like the ability to point the tsconfig file at a different filename when running generate-readme e.g. `my-tsconfig.json`
I've added a flag following the same format and description as the README path.
Thanks!

Feat: allow for a custom tsconfig path during readme generation

---

templates/cli/shared/.github/workflows/onRelease.yml.ejs

fix: #1663
This pull request includes changes to the release workflow in the `onRelease.yml.ejs` file. The most important changes involve adding steps to the build process.
Enhancements to the build process:
* [`templates/cli/shared/.github/workflows/onRelease.yml.ejs`](diffhunk://#diff-15f9e65216eab68234996f9d4ee7722e043b6c259cb00234dac2f40eb5d5bab3R16-R21): Added steps to run `build`, `prepack`, and `postpack` commands in the release workflow.

fix: update onRelease workflow template to include build and prepack steps

---

docs/generate.md
docs/init.md
docs/manifest.md
docs/pack.md
docs/promote.md
docs/readme.md
docs/upload.md
package.json
src/commands/pack/win.ts

Fixes: https://github.com/forcedotcom/cli/issues/3161
The windows tarball bin gets CLI's node options in the cmd file:
https://github.com/oclif/oclif/blob/356ac3253433bf52184e2ae75574ac09a02e4236/src/tarballs/bin.ts#L43
the installer one doesn't:
https://github.com/oclif/oclif/blob/356ac3253433bf52184e2ae75574ac09a02e4236/src/commands/pack/win.ts#L26
@W-17637923@

fix: include `nodeOptions` in win installer bin

---

README.md

This PR fixes a broken link I came across while reading your docs.

docs: fix broken contributing guide link

---

.github/workflows/test.yml
package.json
src/commands/pack/deb.ts
src/commands/upload/tarballs.ts
src/tarballs/build.ts
src/tarballs/config.ts
test/helpers/helper.ts
test/integration/cli.test.ts
test/integration/publish.test.ts
yarn.lock

- Skip linux-arm and win32-x86 targets on Node 24 since binaries are no longer available for them: https://nodejs.org/dist/v24.4.1/
- Test against lts and latest node versions

feat: filter targets that are no longer supported in node 24
