- README.md
- src/app_command.ts
- src/generators/app.ts
- test/run.js
Closes https://github.com/oclif/oclif/issues/51
> Add TSLint optional

- GETTING_STARTED.md
got confused, is this fix correct?
> getting started with oclif without npx guide

- .circleci/config.yml
- src/generators/app.ts
- templates/circle.yml.ejs
- yarn.lock
it is confusing for contributors and I can edit the commit message when I squash anyways
> fix: remove commitlint

- package.json
- yarn.lock
> [FIX] Bump @oclif/command dependency to latest version

- src/generators/app.ts
- templates/README.md.ejs
Addresses PR #68 
CircleCI is now an option in the CLI with a default to true, the same as Mocha.
> feat: make circleci optional

- src/generators/app.ts
this forces saving to package.json even if save=false is set in npmrc
> fix: always use --save with npm

- src/generators/app.ts
> fix: don't include mocha types on no mocha

- src/generators/app.ts
Fixes https://github.com/oclif/oclif.github.io/issues/47
> fix: update globby

- src/generators/app.ts
> fix: bump nyc version in generator

- src/generators/app.ts
Fixes #252 
Note https://github.com/oclif/dev-cli/issues/121
> fix: include dev-cli in single cli & run readme

- .circleci/config.yml
- package.json
- src/generators/app.ts
- yarn.lock
> feat: use plugin-help v3

- src/tarballs/build.ts
Executes `pretarball` script after the bin scripts have been written
> fix: move pretarball step

- package.json
- yarn.lock
> fix: force build to pickup latest oclif/core

- .circleci/config.yml
> Revert "fix: remove context var from job def"

- src/commands/readme.ts
- use summary field for command if available
- use `additionalVersionFlags` when rendering usage
@W-9904239@
> fix: use summary field if available

- .circleci/config.yml
> ci: fix jobs run with sf orb & rm nightly cron

- src/commands/pack/win.ts
This makes the version info accessible to things like the control panel / winget
> feat: add version info to registry for windows installers

- src/generators/cli.ts
> fix: correct package name

- package.json
- yarn.lock
> fix: remove unnecessary dependency

- src/commands/upload/deb.ts
- src/commands/upload/macos.ts
- src/commands/upload/win.ts
Removes references to `oclif-dev` in error messages
[skip-validate-pr]
> fix: update error messages

- .circleci/config.yml
- .circleci/loadgpg
Removes the unnecessary loadgpg script
> chore: remove loadgpg

- src/tarballs/node.ts
- shasum is a perl script, ignore it
- windows don't exist /dev/null
> fix win32 issue

- .github/workflows/test.yml
adds env that normal UT workflow doesn't have
> ci: ut with secrets in env

- package.json
- src/commands/generate.ts
- src/commands/generate/command.ts
- src/commands/generate/hook.ts
- src/commands/manifest.ts
- src/commands/promote.ts
- src/commands/readme.ts
- src/help-compatibility.ts
- src/log.ts
- src/tarballs/config.ts
- yarn.lock
Uses [@oclif/core v2](https://github.com/oclif/core/pull/588)
> feat: use oclif/core v2

- templates/src/command.ts.ejs
> fix: command template

- src/commands/promote.ts
See: https://github.com/oclif/oclif/issues/770 and https://github.com/oclif/oclif/issues/1074
@W-13037040@
> fix(promote:deb): skip i386 deb pkg if node < 10

- src/tarballs/build.ts
to close https://github.com/oclif/oclif/pull/1071
tested with yarn 1, 2, 3 on the Salesforce CLI v2
> fix: add yarn 1/3 support

- src/generators/cli.ts
> feat: add esm option to generate

- package.json
- src/tarballs/node.ts
- yarn.lock
> Retry node download (#1184)

- src/commands/readme.ts
Allows you to pass `--version` and `--repository-prefix` to `oclif readme`. 
Adds the `OCLIF_NEXT_VERSION` fallback on the `--version` flag. TIL that `env` was a flag property.
[@W-13887925@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-13887925)
https://github.com/salesforcecli/github-workflows/pull/68
> Add version and repo-prefix flags to oclif readme

- package.json
- yarn.lock
This PR removes ununsed dep `concurrently`
https://github.com/search?q=repo%3Aoclif%2Foclif%20%2Fconcurrently%2F&type=code
> fix: remove `concurrently` dep

- src/commands/readme.ts
> feat: configurable readme path

- src/commands/readme.ts
> feat: configurable readme path (#1220)

- src/tarballs/bin.ts
- src/tarballs/build.ts
- src/tarballs/config.ts
> feat: add node.options (#1238)

- src/version-indexes.ts
Use the appropriate method to transform response from AWS to JSON
> fix: use transformToString

- .github/workflows/test.yml
- package.json
- src/generators/cli.ts
- src/generators/command.ts
- src/generators/hook.ts
- src/tarballs/build.ts
- src/tarballs/node.ts
- src/util.ts
- tsconfig.json
- yarn.lock
Use `sort-package-json` to sort the generated package.json
**QA**
- `bin/dev.js generate my-cli`
- Is generated package.json sorted according to [these rules](https://github.com/keithamus/sort-package-json/blob/HEAD/defaultRules.md)?
> fix: sort generated package.json

- src/tarballs/build.ts
> fix: force local paths when extracting on win32 (#1322)

- .github/workflows/test.yml
- package.json
- src/commands/generate.ts
- src/commands/init.ts
- src/generator.ts
- templates/src/init/dev.cmd.ejs
- templates/src/init/dev.js.ejs
- templates/src/init/run.cmd.ejs
- templates/src/init/run.js.ejs
- test/integration/cli.test.ts
- test/integration/init.test.ts
- test/integration/util.ts
> feat: add init command (#1358)

- src/commands/init.ts
> fix: supporting paths with spaces whilst running chmod (#1367)

- test/integration/deb.test.ts
> test: fix deb integration tests

- package.json
- src/commands/generate/hook.ts
- src/commands/manifest.ts
- src/commands/pack/win.ts
- src/generator.ts
- src/log.ts
- src/readme-generator.ts
- src/tarballs/build.ts
- src/tarballs/config.ts
- src/upload-util.ts
- test/integration/deb.test.ts
- test/unit/readme-generator.test.ts
- yarn.lock
Use @oclif/core v4
@W-15845231@
> feat: use @oclif/core v4

- src/commands/init.ts
- templates/cli/shared/package.json.ejs
Generate new CLIs with oclif/core v4
> feat: generate cli with core v4

- src/commands/generate.ts
- src/generator.ts
- Adds a `--dry-run` flag to `oclif generate`
- Adds debug logs for `oclif generate`
> feat: dry-run flag and debug logs for generate

- templates/cli/esm/bin/dev.js.ejs
> fix: update esm dev.js shebang

- src/tarballs/build.ts
* fix: add pnpm lock option
* fix: include pretarball
Merges #1527
> fix: add pnpm lock option (#1527)

- docs/generate.md
- docs/init.md
- docs/manifest.md
- docs/pack.md
- docs/promote.md
- docs/readme.md
- docs/upload.md
- package.json
- src/commands/pack/win.ts
- src/commands/upload/win.ts
- src/tarballs/build.ts
- src/tarballs/config.ts
- src/tarballs/node.ts
Pack win32-arm64 tarballs/installers (only supported for node 20+)
Test run with sf: https://github.com/salesforcecli/cli/actions/runs/11059244471
Fixes #1557
@W-16810768@
> feat: pack win32-arm64 tarballs

- src/aws.ts
- src/commands/promote.ts
- Add `--ignore-missing` to `oclif promote` to allow users to ignore any failures from oclif attempting to promote non-existent objects
- Add suggestions for when a promotion is attempted on a non-existent object
- Make `oclif promote` output slightly more readable
**with `--ignore-missing`**
**without `--ignore-missing`**
> fix: add --ignore-missing to promote

- src/commands/pack/tarballs.ts
- src/tarballs/build.ts
Solves https://github.com/oclif/oclif/issues/1593
> feat: allow pack:tarball on windows

- package.json
I found this package by chance, only after I looked at the first few pages on the NPM with the key word CLI
Perhaps it is worth adding this keyword to find this package easier?
> chore: add cli keyword

- CHANGELOG.md
- docs/generate.md
- docs/init.md
- docs/manifest.md
- docs/pack.md
- docs/promote.md
- docs/readme.md
- docs/upload.md
- package.json
- src/tarballs/build.ts
- src/tarballs/config.ts
- yarn.lock
Resolves https://github.com/oclif/oclif/issues/1759
Dependency upgrade: https://github.com/oclif/core/pull/1400
> feat: support --no-xattrs flag for darwin

- src/commands/promote.ts
- src/commands/upload/tarballs.ts
- src/upload-util.ts
- src/version-indexes.ts
- test/integration/win.test.ts
> feat: enable uploads from windows machines (#1815)

- src/commands/generate.ts
> fix(W-19083920): make readdir work on node 24
